### PR TITLE
fix(check_crs_terra): Prefix `terra:crs()` call

### LINKED ISSUE #893: addPolyline() with SpatVector fails if terra is not loaded because check_crs_terra() is missing depency terra::crs
When `{terra}` is not loaded (e.g., individual `{terra}` functions are imported into package namespace) functions that internally call `check_crs_terra()` will fail. I think this is because `check_crs_terra()` simply calls `crs()` instead of `terra::crs()`:
https://github.com/rstudio/leaflet/blob/d8c97944df7aa788dce0b4834eb250b13f34ba78/R/normalize-terra.R#L74-L94

I encounter this issue when calling `addPolylines()` with `SpatVector` objects.

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #893

### CODE REVIEW

File: R/normalize-terra.R [hunk 1]
```diff
@@ -53,7 +53,7 @@ polygonData.SpatVector <- function(obj) {
 assure_crs_terra <- function(x) {
```
Comment (schloerke) [inline R/normalize-terra.R:53]: Can we drop this function? 

https://github.com/rstudio/leaflet/pull/808#issuecomment-1533950559

File: R/normalize-terra.R [hunk 2]
```diff
@@ -82,7 +84,7 @@ check_crs_terra <- function(x) {
     warning("SpatVector layer is not long-lat data", call. = FALSE)
   }
 
-  prj <- crs(x, proj=TRUE)
```
Comment (schloerke) [inline R/normalize-terra.R:85]: Thank you!
